### ISSUE TITLE
Consider adding connexion support

### ISSUE THREAD

**Issue by donbowman** [thangbn/json-logging-python#18]
https://github.com/zalando/connexion/issues/640 shows that its a pain for people to create json logging w/ connexion.

but its essentially flask i think.

**Comment by thangbn** [comment]
@donbowman  PR welcome. currently, I'm super busy so not really looking to implement any new feature except bug fixing. Take a look here on how to add support for new framework:
https://github.com/thangbn/json-logging-python#5-framework-support-plugin-development
thanks

**Comment by bhechinger** [comment]
So just treating it like flask seems to work for me, however I'm not able to customize the output.

```
app = connexion.App(__name__, specification_dir='./')

# Read the swagger.yml file to configure the endpoints
app.add_api('AuthServer.yaml')

application = app.app
application.logger.setLevel(logging.DEBUG)
json_logging.ENABLE_JSON_LOGGING = True
json_logging.init(framework_name='flask')
json_logging.init_request_instrument(application)
```

If I change the init to:

```
json_logging.init(framework_name='flask', custom_formatter=CustomJSONLog)
```

Using your example custom format it seems like that gets ignored.
