### ISSUE TITLE
save connexion logs to file

### ISSUE THREAD

**Issue by richardpatsch** [thangbn/json-logging-python#23]
if I configure the logger according to the documentation and add a TimeRotatingHandler:

```python
# Create the application instance
app = connexion.App(__name__, specification_dir='./')

json_logging.ENABLE_JSON_LOGGING = True
json_logging.init(framework_name='connexion')
json_logging.init_request_instrument(app)

logger = logging.getLogger("test-logger")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler(sys.stdout))

handler = TimedRotatingFileHandler('logs/info.log', 'midnight', 1, utc=True)
logger.addHandler(handler)
```
it only writes logger.info... logs, but not the request logs. They are only in the console. 
I also tried this:

```python
logger = logging.getLogger("connexion-request-logger")
logger.addHandler(TimedRotatingFileHandler('logs/info.log', 'midnight', 1, utc=True))
```
but compared to the request logs there are several fields missing (and type is "logs" instead of "request")

How is it possible write those logs to a file correctly?

thanks in advance!

**Comment by thangbn** [comment]
I'm busy recently, will try to take a look if have time

**Comment by thangbn** [comment]
1.0.2 address this.
https://github.com/thangbn/json-logging-python/releases/tag/1.0.2
