### ISSUE TITLE
Question - please explain COMPONENT_ID and COMPONENT_NAME

### ISSUE THREAD

**Issue by danizen** [thangbn/json-logging-python#38]
`json_logging.COMPONENT_ID` and `json_logging.COMPONENT_NAME` seem to be mean't to be customized.  Is there a mechanism to read these from framework settings?  If not, how are these mean't to be used.

**Comment by thangbn** [comment]
the value can be easily to override by assigned it value directly before init the logging. similar to **ENABLE_JSON_LOGGING** value: 
https://github.com/thangbn/json-logging-python#21-non-web-application-log
