### ISSUE TITLE
Publish missing sdist's to PyPI

### ISSUE THREAD

**Issue by twosigmajab** [thangbn/json-logging-python#42]
Version 0.0.1 is the only version of json-logging available on PyPI that provides an sdist (source distribution). All the other versions, and in particular the latest version (1.0.6), only make wheels available.[1]

This is a problem because not all consumers can consume the bdist_wheel distributions, but can consume the sdists. (Hitting this myself prompted me to open this issue.) For reference, the [various](https://pythonwheels.com/) packaging [guides](https://packaging.python.org/tutorials/packaging-projects/) all advise providing sdist along with bdist_wheel; wheels complement sdists, they don't replace them.

Thanks for maintaining json-logging!

[1] Quoting https://pypi.app.twosigma.com/pypi/simple/json-logging/
> json-logging-0.0.1.tar.gz
> json_logging-0.0.1-py2.py3-none-any.whl
> json_logging-0.0.10-py2.py3-none-any.whl
> json_logging-0.0.11-py2.py3-none-any.whl
> json_logging-0.0.12-py2.py3-none-any.whl
> json_logging-0.0.13-py2.py3-none-any.whl
> json_logging-0.0.8-py2.py3-none-any.whl
> json_logging-0.0.9-py2.py3-none-any.whl
> json_logging-0.1.0-py2.py3-none-any.whl
> json_logging-0.1.1-py2.py3-none-any.whl
> json_logging-0.1.2-py2.py3-none-any.whl
> json_logging-1.0.0-py2.py3-none-any.whl
> json_logging-1.0.1-py2.py3-none-any.whl
> json_logging-1.0.2-py2.py3-none-any.whl
> json_logging-1.0.3-py2.py3-none-any.whl
> json_logging-1.0.4-py2.py3-none-any.whl
> json_logging-1.0.5-py2.py3-none-any.whl
> json_logging-1.0.6-py2.py3-none-any.whl

**Comment by thangbn** [comment]
thanks for letting me know that, from now i will include a source dist. i added source dist for lastest version btw.

**Comment by twosigmajab** [comment]
Thanks @thangbn, much better now! 😊
