### ISSUE TITLE
[Question] Is there a way to exclude a specific API endpoints from logging requests?

### ISSUE THREAD

**Issue by randykinne** [thangbn/json-logging-python#44]
I tried looking through the code to find where this may be possible but I couldn't find anything. There are also no examples of this.

**Comment by randykinne** [comment]
Forgot to explain it more before hitting send:
I have API endpoints that are used in kubernetes health checks - logging those requests would not be necessary as they are sent roughly 10x per minute. Is there any way to disable request logging for specific endpoints?

**Comment by thangbn** [comment]
there is not a way to do this but definitely doable, PR is welcome btw. current to busy to handle it, I need to take care of my kids when they are at home due to Covid-19 🤣

**Comment by thangbn** [comment]
fixed in version 1.2.5

**Comment by randykinne** [comment]
Thank you!
