### ISSUE TITLE
[Question] Is there a way to use json_logging.config_root_logger with custom formatter

### ISSUE THREAD

**Issue by sainoba** [thangbn/json-logging-python#50]
Currently when using `json_logging.config_root_logger()` it uses either  `JSONLogFormatter` or `JSONLogWebFormatter`.

Is there a way to set it up so it uses a customer formatter?

**Comment by thangbn** [comment]
@sainoba addressed in 1.2.2, you need to pass the customer formatter in the **init** method, after that call json_logging.config_root_logger then the root logger will be configured to use that custom formatter

**Comment by sainoba** [comment]
Awesome, thanks for the quick response.
