### ISSUE TITLE
[Flask] Correlation ID gets added regardless of create_correlation_id_if_not_exists = False

### ISSUE THREAD

**Issue by Alex-online** [thangbn/json-logging-python#7]
Hey,

First of all great package. Really makes it easy to log to the ELK stack. 

I'm having an issue regarding the correlation ID. Basically, I've set "create_correlation_id_if_not_exists" to False at the start of my Flask application:

```# Set up logging
json_logging.ENABLE_JSON_LOGGING = True
json_logging.init(framework_name='flask')
json_logging.init_request_instrument(app)
logger = logging.getLogger("test-logger")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler(sys.stdout))
json_logging.COMPONENT_NAME = "frontend"
json_logging.CREATE_CORRELATION_ID_IF_NOT_EXISTS = False
```

However, whenever I request the homepage, which should not generate correlation ID's, I still see a correlation ID in my log. Example:

```
{
    "type":"request",
    "written_at":"2018-11-07T13:45:24.861Z",
    "written_ts":1541598324861734000,
    "component_id":"-",
    "component_name":"frontend",
    "component_instance":0,
    "correlation_id":"60e6ef86-e293-11e8-9222-d017c209b59b",
    "remote_user":"-",
    "request":"/favicon.ico",
    "referer":"-",
    "x_forwarded_for":"-",
    "protocol":"HTTP/1.1",
    "method":"GET",
    "remote_ip":"127.0.0.1",
    "request_size_b":-1,
    "remote_host":"127.0.0.1",
    "remote_port":63896,
    "request_received_at":"2018-11-07T13:45:24.860Z",
    "response_time_ms":1,
    "response_status":404,
    "response_size_b":233,
    "response_content_type":"text/html",
    "response_sent_at":"2018-11-07T13:45:24.861Z"
 }
```

And this is my homepage route:

```@app.route('/')
def index():
    return render_template('index.html')
```

As you can see I don't manually add the ID in there.

Using the following packages:
```Flask==1.0.2
Flask-RESTful==0.3.6
json-logging==0.0.9
mongoengine==0.15.3
requests==2.20.0
```

Do you know why the ID still gets added?

**Comment by thangbn** [comment]
@Alex-online  will take a look

**Comment by thangbn** [comment]
@Alex-online  actually its not a problem, just make sure you configure json_logging before you you call json_logging.init, something like this:
```python
app = flask.Flask(__name__)
json_logging.ENABLE_JSON_LOGGING = True
json_logging.CREATE_CORRELATION_ID_IF_NOT_EXISTS = False
json_logging.init(framework_name='flask')
json_logging.init_request_instrument(app)
```

**Comment by darox** [comment]
I have a question that Is may related to this topic. My correlation ID populated by the logger is not the same, as the one created by my code instrumentation with open telemtry. Will these steps solve this issue?

**Comment by bobbui** [comment]
@darox u can manually set the correlation id from open telemetry into the log statement like this:  https://github.com/bobbui/json-logging-python#forced-overriding-correlation-id
